environment:
    matrix:
        - PYTHON: C:\\Python27
        - PYTHON: C:\\Python33
        - PYTHON: C:\\Python34

install:
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - pip install -r requirements-dev.txt

build: off

test_script:
    - nosetests tests/unit
    - nosetests tests/functional/projects
    - nosetests tests/functional/test_build_environment.py
    - nosetests tests/functional/test_development_mode.py
    - nosetests tests/functional/test_directory_source.py
    - nosetests tests/functional/test_xcconfig.py
